/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas7;

import java.sql.ResultSet;

/**
 *
 * @author ROG G513RM
 */
public class MahasiswaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MahasiswaFrame.class.getName());

    /**
     * Creates new form Mahasiswa
     */
    public MahasiswaFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        addNama();
    }

    private void addNama(){
        ResultSet res;
        Namacmb.removeAllItems();
        Nimcmb.removeAllItems();
        try {
            Koneksi.getKoneksi();
            String query = "SELECT nim, nama FROM mhs ORDER BY nama";
            res = Koneksi.stmt.executeQuery(query);

            while (res.next()) {
                Namacmb.addItem(res.getString("Nama"));
                Nimcmb.addItem(res.getString("Nim"));
            }
        } catch (Exception e){
            System.err.println("Koneksi Gagal " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nimlbl = new javax.swing.JLabel();
        Namalbl = new javax.swing.JLabel();
        Alamatlbl = new javax.swing.JLabel();
        Nohplbl = new javax.swing.JLabel();
        Kotalbl = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        txthp = new javax.swing.JTextField();
        txtkota = new javax.swing.JTextField();
        Simpanbtn = new javax.swing.JButton();
        Hapusbtn = new javax.swing.JButton();
        Ubahbtn = new javax.swing.JButton();
        Batalbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Nimcmb = new javax.swing.JComboBox<>();
        Namacmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nimlbl.setText("NIM");

        Namalbl.setText("NAMA");

        Alamatlbl.setText("ALAMAT");

        Nohplbl.setText("NO_HP");

        Kotalbl.setText("KOTA");

        txtalamat.setText("txtalamat");
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });

        txthp.setText("txtno_hp");

        txtkota.setText("txtkota");

        Simpanbtn.setText("Simpan");
        Simpanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanbtnActionPerformed(evt);
            }
        });

        Hapusbtn.setText("Hapus");
        Hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusbtnActionPerformed(evt);
            }
        });

        Ubahbtn.setText("Ubah");
        Ubahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahbtnActionPerformed(evt);
            }
        });

        Batalbtn.setText("Batal");
        Batalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalbtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Nimcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Nimcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NimcmbActionPerformed(evt);
            }
        });

        Namacmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Simpanbtn)
                        .addGap(18, 18, 18)
                        .addComponent(Hapusbtn)
                        .addGap(18, 18, 18)
                        .addComponent(Ubahbtn)
                        .addGap(18, 18, 18)
                        .addComponent(Batalbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Namalbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nimlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Alamatlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nohplbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Kotalbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txthp)
                            .addComponent(txtkota)
                            .addComponent(Nimcmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Namacmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(379, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nimlbl)
                    .addComponent(Nimcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namalbl)
                    .addComponent(Namacmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alamatlbl)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nohplbl)
                    .addComponent(txthp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kotalbl)
                    .addComponent(txtkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpanbtn)
                    .addComponent(Hapusbtn)
                    .addComponent(Ubahbtn)
                    .addComponent(Batalbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void SimpanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimpanbtnActionPerformed

    private void HapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusbtnActionPerformed

    private void UbahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbahbtnActionPerformed

    private void BatalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BatalbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void NimcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NimcmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NimcmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MahasiswaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamatlbl;
    private javax.swing.JButton Batalbtn;
    private javax.swing.JButton Hapusbtn;
    private javax.swing.JLabel Kotalbl;
    private javax.swing.JComboBox<String> Namacmb;
    private javax.swing.JLabel Namalbl;
    private javax.swing.JComboBox<String> Nimcmb;
    private javax.swing.JLabel Nimlbl;
    private javax.swing.JLabel Nohplbl;
    private javax.swing.JButton Simpanbtn;
    private javax.swing.JButton Ubahbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtkota;
    // End of variables declaration//GEN-END:variables
}
