/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas3;

import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG G513RM
 */
public class Mahasiswa extends javax.swing.JFrame {

    public static Connection con;
    public static Statement stmt;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(Mahasiswa.class.getName());

    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
        initComponents();
        this.setLocationRelativeTo(null);
        // this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        bersih();
        tabelmhs();
    }

    private void bersih() {
        txtnim.setText("");
        txtnama.setText("");
        txtalamat.setText("");
        txthp.setText("");
        txtkota.setText("");
        autonumber();
    }

    // Catatan: Jika ingin menggunakan tipe 'int', angka harus dikurangi menjadi 1000000000
    // agar tidak melebihi batas maksimal int (2.147.483.647).
    // Di sini penggunaan tipe data 'long' lebih aman agar program tidak crash
    // apabila NIM / ID mahasiswa dari database berjumlah 10 digit atau lebih.
    private void autonumber() {
        ResultSet res;
        String strnim;
        long longnim;
        try {
            Koneksi.getKoneksi();
            String query = "Select nim from mhs order by nim";
            res = Koneksi.stmt.executeQuery(query);
            while (res.next()) {
                strnim = res.getString("nim");
                longnim = Long.parseLong(strnim) + 1; // Cukup tambahkan 1
                txtnim.setText(String.valueOf(longnim));
            }
        } catch (Exception e) {
            System.err.println("Koneksi gagal" + e.getMessage());
            txtnim.setText("10000000001");
        }
    }

    private void autoNumberParam(String param){
        ResultSet res;
        String strnim, strkode;
        long longnim;
        // Ambil huruf pertama (dan jadikan huruf besar agar konsisten)
        strkode = param.substring(0, 1).toUpperCase();

        try {
            Koneksi.getKoneksi();
            String query = "SELECT nim FROM mhs WHERE LEFT(nama, 1) = '" + strkode + "' ORDER BY nim";
            res = Koneksi.stmt.executeQuery(query);
            
            // Cek apakah ada datanya
            if (res.last()) {
                strnim = res.getString("nim");
                // Hilangkan semua huruf pada NIM lama agar bisa diubah jadi angka
                String pureNumber = strnim.replaceAll("[^0-9]", "");
                longnim = Long.parseLong(pureNumber) + 1;
                strnim = String.valueOf(longnim);
                txtnim.setText(strkode + strnim);
            } else {
                // Jika data masih kosong untuk awalan huruf tersebut
                txtnim.setText(strkode + "1000000001");
            }
        } catch (Exception e) {
            System.err.println("Koneksi gagal" + e.getMessage());
            // Berikan awalan huruf meskipun error / data kosong
            txtnim.setText(strkode + "1000000001");
        }
    }

    private void tabelmhs() {
        ResultSet res;
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("NIM");
        tb.addColumn("NAMA");
        tb.addColumn("ALAMAT");
        tb.addColumn("NO_HP");
        tb.addColumn("KOTA");
        jTable1.setModel(tb);
        try {
            // String url = "jdbc:mysql://localhost/db_pemdas";
            // String user = "root";
            // String pass = "";
            // con = DriverManager.getConnection(url, user, pass);
            // stmt = con.createStatement();
            Koneksi.getKoneksi();
            String query = "Select * from mhs";
            res = Koneksi.stmt.executeQuery(query);
            while (res.next()) {
                tb.addRow(new Object[] {
                        res.getString("nim"),
                        res.getString("nama"),
                        res.getString("alamat"),
                        res.getString("hp"),
                        res.getString("kota")
                });
            }
            jTable1.setModel(tb);
            System.out.println("Data berhasil ditampilkan");
        } catch (Exception e) {
            System.err.println("Koneksi gagal" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txthp = new javax.swing.JTextField();
        txtkota = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("NAMA");

        jLabel3.setText("ALAMAT");

        jLabel4.setText("NO_HP");

        jLabel5.setText("KOTA");

        txtnim.setText("txtnim");
        txtnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnimActionPerformed(evt);
            }
        });

        txtnama.setText("txtnama");
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamaFocusLost(evt);
            }
        });

        txtalamat.setText("txtalamat");
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });

        txthp.setText("txtno_hp");

        txtkota.setText("txtkota");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Rubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtnama)
                            .addComponent(txtnim)
                            .addComponent(txthp)
                            .addComponent(txtkota))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusLost
        // TODO add your handling code here:
        autoNumberParam(txtnama.getText());
    }//GEN-LAST:event_txtnamaFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String perintah = "DELETE FROM mhs WHERE nim = '" + txtnim.getText() + "'";
        Koneksi.ubahData(perintah);
        tabelmhs();
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String perintah = "UPDATE mhs set nama='" + txtnama.getText() + "', alamat = '" + txtalamat.getText()
                + "', hp = '" + txthp.getText() + "', kota = '" + txtkota.getText() + "' where nim = '"
                + txtnim.getText() + "'";
        Koneksi.ubahData(perintah);
        tabelmhs();
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bersih();
        autonumber();
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int no = jTable1.getSelectedRow();
        txtnim.setText(jTable1.getValueAt(no, 0).toString());
        txtnama.setText(jTable1.getValueAt(no, 1).toString());
        txtalamat.setText(jTable1.getValueAt(no, 2).toString());
        txthp.setText(jTable1.getValueAt(no, 3).toString());
        txtkota.setText(jTable1.getValueAt(no, 4).toString());

    }// GEN-LAST:event_jTable1MouseClicked

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtalamatActionPerformed

    private void txtnimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtnimActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtnimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String perintah = "INSERT INTO mhs (nim, nama, alamat, hp, kota) values ('" + txtnim.getText() + "', '" + txtnama.getText() + "', '"
                + txtalamat.getText() + "', '" + txthp.getText() + "', '" + txtkota.getText() + "')";
        Koneksi.ubahData(perintah);
        tabelmhs();
        autoNumberParam(txtnama.getText());
    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    // End of variables declaration//GEN-END:variables
}
