/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Tugas2;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author ROG G513RM
 */
public class mainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(mainFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public mainFrame() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0, 0, screenSize.width, screenSize.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MUtama = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        Master = new javax.swing.JMenu();
        Mahasiswa = new javax.swing.JMenuItem();
        Penduduk = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        Laporan = new javax.swing.JMenu();
        Konfigurasi = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MUtama.setText("Menu Utama");

        jMenuItem1.setLabel("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MUtama.add(jMenuItem1);

        jMenuItem2.setLabel("Logout");
        MUtama.add(jMenuItem2);
        MUtama.add(jSeparator1);

        jMenuItem3.setLabel("Keluar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MUtama.add(jMenuItem3);

        jMenuBar1.add(MUtama);

        Master.setText("Master");
        Master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterActionPerformed(evt);
            }
        });

        Mahasiswa.setLabel("Mahasiswa");
        Master.add(Mahasiswa);

        Penduduk.setLabel("Penduduk");
        Penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendudukActionPerformed(evt);
            }
        });
        Master.add(Penduduk);

        jMenuBar1.add(Master);

        Transaksi.setText("Transaksi");
        jMenuBar1.add(Transaksi);

        Laporan.setText("Laporan");
        jMenuBar1.add(Laporan);

        Konfigurasi.setText("Konfigurasi");
        jMenuBar1.add(Konfigurasi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PendudukActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PendudukActionPerformed
        // TODO add your handling code here:
        JFrame pend = new frmPenduduk();
        pend.setExtendedState(JFrame.NORMAL);
        pend.setVisible(true);

    }// GEN-LAST:event_PendudukActionPerformed

    private void MasterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MasterActionPerformed
        // TODO add your handling code here:
        JFrame mhs = new frmMahasiswa();
        mhs.setExtendedState(JFrame.NORMAL);
        mhs.setVisible(true);

    }// GEN-LAST:event_MasterActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Object[] options = { "Ya Silahkan", "Tidak Terimakasih" };
        int choice = JOptionPane.showOptionDialog(
                null,
                "Aplikasi Akan Ditutup?",
                "Confirmation Dialogue",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        if (choice == JOptionPane.YES_OPTION) {
            System.out.println("Terimakasih");
            System.exit(0);
        } else if (choice == JOptionPane.NO_OPTION) {
            System.out.println("Tidak Jadi");
        }

    }// GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Konfigurasi;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenu MUtama;
    private javax.swing.JMenuItem Mahasiswa;
    private javax.swing.JMenu Master;
    private javax.swing.JMenuItem Penduduk;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
