/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemdas_quiz_final;

import java.sql.Connection;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ROG G513RM
 */
public class FramePembelian extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePembelian.class.getName());

    // Tombol Next ditambahkan programatik karena tidak ada di GUI Builder
    private JButton btnNext;

    /**
     * Creates new form FramePembelian
     */
    public FramePembelian() {
        initComponents();
        setLocationRelativeTo(null);

        // Tambahkan tombol Next secara programatik
        tambahTombolNext();

        // Inisialisasi data saat frame dibuka
        inisialisasiFrame();
    }

    // Menambahkan tombol Next/Lanjut ke panel bawah
    private void tambahTombolNext() {
        btnNext = new JButton("Lanjut →");

        javax.swing.JPanel panelBawah = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        panelBawah.add(btnNext);

        getContentPane().add(panelBawah, java.awt.BorderLayout.SOUTH);
        pack();
    }

    // Mengisi data awal: tanggal hari ini, nomor pesanan otomatis, dan data supplier
    private void inisialisasiFrame() {
        // Isi tanggal hari ini secara otomatis dan jadikan read-only
        txtTanggal.setText(LocalDate.now().toString());
        txtTanggal.setEditable(false);

        // Generate nomor pesanan otomatis dan jadikan read-only
        txtNoPesanan.setText(Koneksi.generateNoPesanan());
        txtNoPesanan.setEditable(false);

        // Muat data supplier ke ComboBox
        muatDataSupplier();

        // Tombol Lanjut: validasi lalu buka FramePembelianDetail
        btnNext.addActionListener(e -> lanjutKeDetail());
    }

    // Memuat data supplier dari database ke ComboBox
    private void muatDataSupplier() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("-- Pilih Supplier --");

        try {
            Connection c = Koneksi.getKoneksi();
            String sql   = "SELECT kd_supplier, nama_supplier FROM tb_supplier ORDER BY kd_supplier";
            ResultSet rs = c.createStatement().executeQuery(sql);

            while (rs.next()) {
                // Format: "S00001 - Nama Supplier"
                model.addElement(rs.getString("kd_supplier") + " - " + rs.getString("nama_supplier"));
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data supplier: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        cmbSupplier.setModel(model);
    }

    // Validasi input lalu buka FramePembelianDetail dengan parameter yang diperlukan
    private void lanjutKeDetail() {
        // Validasi: supplier harus dipilih (bukan item default)
        if (cmbSupplier.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Pilih supplier terlebih dahulu!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ambil kode supplier dari pilihan ComboBox (bagian sebelum " - ")
        String pilihanSupplier = cmbSupplier.getSelectedItem().toString();
        String kdSupplier      = pilihanSupplier.split(" - ")[0];
        String noPesanan       = txtNoPesanan.getText();
        String tanggal         = txtTanggal.getText();

        // Buka frame detail dan passing parameter transaksi
        FramePembelianDetail frameDetail = new FramePembelianDetail(noPesanan, tanggal, kdSupplier);
        frameDetail.setVisible(true);
        this.dispose(); // Tutup frame ini
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoPesanan = new javax.swing.JLabel();
        txtNoPesanan = new javax.swing.JTextField();
        lblTanggal = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        lblSupplier = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNoPesanan.setText("No. Pesanan:");

        txtNoPesanan.setText("jTextField1");

        lblTanggal.setText("Tanggal:");

        txtTanggal.setText("jTextField1");

        lblSupplier.setText("Supplier:");

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoPesanan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTanggal, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNoPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoPesanan)
                    .addComponent(txtNoPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //GEN-BEGIN:variables
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePembelian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel lblNoPesanan;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTextField txtNoPesanan;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
