/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemdasquizlagi;

import java.awt.Frame;

/**
 *
 * @author ROG G513RM
 */
public class FramePembelianPilih extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(FramePembelianPilih.class.getName());

    /**
     * Creates new form FramePembelianPilih
     */
    public FramePembelianPilih() {
        initComponents();
        setTitle("Form Pilih");
        setExtendedState(Frame.NORMAL);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnTambahPembelian = new javax.swing.JButton();
        btnCekPembelian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnTambahPembelian.setText("Tambah");
        btnTambahPembelian.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnTambahPembelianActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(93, 81, 106, 0);
        getContentPane().add(btnTambahPembelian, gridBagConstraints);

        btnCekPembelian.setText("Cek");
        btnCekPembelian.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCekPembelianActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(93, 18, 106, 100);
        getContentPane().add(btnCekPembelian, gridBagConstraints);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btnTambahPembelianActionPerformed(
        java.awt.event.ActionEvent evt
    ) {
        //GEN-FIRST:event_btnTambahPembelianActionPerformed
        // TODO add your handling code here:
        FramePembelian framePembelian = new FramePembelian();
        framePembelian.setVisible(true);
    } //GEN-LAST:event_btnTambahPembelianActionPerformed

    private void btnCekPembelianActionPerformed(
        java.awt.event.ActionEvent evt
    ) {
        //GEN-FIRST:event_btnCekPembelianActionPerformed
        // TODO add your handling code here:
        FramePembelianCek framePembelianEdit = new FramePembelianCek();
        framePembelianEdit.setVisible(true);
    } //GEN-LAST:event_btnCekPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
            new FramePembelianPilih().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekPembelian;
    private javax.swing.JButton btnTambahPembelian;
    // End of variables declaration//GEN-END:variables
}
