/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemdasquizlagi;

import java.awt.Frame;
import javax.swing.JFrame;

/**
 *
 * @author ROG G513RM
 */
public class FrameMaster extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(FrameMaster.class.getName());

    /**
     * Creates new form FrameMaster
     */
    public FrameMaster() {
        initComponents();
        setExtendedState(Frame.NORMAL);
        setLocationRelativeTo(null);
        setTitle("Form Master");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnSupplier = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        btnPembelian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnSupplier.setText("Supplier");
        btnSupplier.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSupplierActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 77, 0, 0);
        getContentPane().add(btnSupplier, gridBagConstraints);

        btnBarang.setText("Barang");
        btnBarang.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBarangActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 77, 74, 0);
        getContentPane().add(btnBarang, gridBagConstraints);

        btnPelanggan.setText("Pelanggan");
        btnPelanggan.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPelangganActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 18, 0, 83);
        getContentPane().add(btnPelanggan, gridBagConstraints);

        btnPembelian.setText("Pembelian");
        btnPembelian.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPembelianActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 74, 83);
        getContentPane().add(btnPembelian, gridBagConstraints);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnSupplierActionPerformed
        // TODO add your handling code here:
        FrameSupplier frameSupplier = new FrameSupplier();
        frameSupplier.setVisible(true);
    } //GEN-LAST:event_btnSupplierActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        FrameBarang frameBarang = new FrameBarang();
        frameBarang.setVisible(true);
    } //GEN-LAST:event_btnBarangActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        FramePelanggan framePelanggan = new FramePelanggan();
        framePelanggan.setVisible(true);
    } //GEN-LAST:event_btnPelangganActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnPembelianActionPerformed
        // TODO add your handling code here:
        FramePembelianPilih framePembelian = new FramePembelianPilih();
        framePembelian.setVisible(true);
    } //GEN-LAST:event_btnPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
            new FrameMaster().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnPembelian;
    private javax.swing.JButton btnSupplier;
    // End of variables declaration//GEN-END:variables
}
