/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas_lebaran;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ROG G513RM
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuUtama = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        Master = new javax.swing.JMenu();
        Mahasiswa = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        Laporan = new javax.swing.JMenu();
        Konfigurasi = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuUtama.setText("Menu Utama");

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        MenuUtama.add(Exit);

        jMenuBar1.add(MenuUtama);

        Master.setText("Master");

        Mahasiswa.setText("Mahasiswa");
        Mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MahasiswaActionPerformed(evt);
            }
        });
        Master.add(Mahasiswa);

        jMenuBar1.add(Master);

        Transaksi.setText("Transaksi");
        jMenuBar1.add(Transaksi);

        Laporan.setText("Laporan");
        jMenuBar1.add(Laporan);

        Konfigurasi.setText("Konfigurasi");
        jMenuBar1.add(Konfigurasi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 277, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        Object[] options = { "Ya", "Tidak" };
        int choice = JOptionPane.showOptionDialog(
                null,
                "Aplikasi Akan Ditutup?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);

        if (choice == JOptionPane.YES_OPTION) {
            System.out.println("Terimakasih");
            System.exit(0);
        } else if (choice == JOptionPane.NO_OPTION) {
            System.out.println("Tidak Jadi");
        }

    }// GEN-LAST:event_ExitActionPerformed

    private void MahasiswaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MahasiswaActionPerformed
        // TODO add your handling code here:
        MhsFrame mhsFrame = new MhsFrame();
        mhsFrame.setVisible(true);
    }// GEN-LAST:event_MahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu Konfigurasi;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem Mahasiswa;
    private javax.swing.JMenu Master;
    private javax.swing.JMenu MenuUtama;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
