/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas_lebaran;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG G513RM
 */
public class MhsFrame extends javax.swing.JFrame {

    public static Connection con;
    public static Statement stmt;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MhsFrame.class.getName());

    /**
     * Creates new form Mahasiswa
     */
    public MhsFrame() {
        initComponents();

        // Atur ukuran frame agar tabel bisa menampilkan banyak baris
        this.setSize(900, 650);

        // Untuk menengahkan frame
        this.setLocationRelativeTo(null);

        // 
        clearText();
        tabelmhs();

        // Listener untuk mengisi form saat baris tabel diklik
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int baris = jTable1.getSelectedRow();
                if (baris >= 0) {
                    txtNIM.setText(jTable1.getValueAt(baris, 0).toString());
                    txtNAMA.setText(jTable1.getValueAt(baris, 1).toString());
                    txtALAMAT.setText(jTable1.getValueAt(baris, 2).toString());
                    txtHP.setText(jTable1.getValueAt(baris, 3).toString());
                    txtKOTA.setText(jTable1.getValueAt(baris, 4).toString());
                }
            }
        });
    }

    // Untuk membersihkan text field
    private void clearText() {
        txtNIM.setText("");
        txtNAMA.setText("");
        txtALAMAT.setText("");
        txtHP.setText("");
        txtKOTA.setText("");
    }

    private void tabelmhs() {
        ResultSet res;
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("NIM");
        tb.addColumn("NAMA");
        tb.addColumn("ALAMAT");
        tb.addColumn("NO_HP");
        tb.addColumn("KOTA");
        jTable1.setModel(tb);
        try {
            // Gunakan KoneksiDtb untuk mendapatkan koneksi, simpan ke variabel con dan stmt
            con = KoneksiDtb.getKoneksi();
            stmt = con.createStatement();
            String query = "Select * from mhs";
            res = stmt.executeQuery(query);
            while (res.next()) {
                tb.addRow(new Object[] {
                        res.getString("nim"),
                        res.getString("nama"),
                        res.getString("alamat"),
                        res.getString("hp"),
                        res.getString("kota")
                });
            }
            jTable1.setModel(tb);
            // Kolom tabel otomatis menyesuaikan lebar layar
            jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            System.out.println("Data berhasil ditampilkan");
        } catch (Exception e) {
            System.err.println("Koneksi gagal" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NIM = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        ALAMAT = new javax.swing.JLabel();
        HP = new javax.swing.JLabel();
        KOTA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNIM = new javax.swing.JTextField();
        txtNAMA = new javax.swing.JTextField();
        txtALAMAT = new javax.swing.JTextField();
        txtHP = new javax.swing.JTextField();
        txtKOTA = new javax.swing.JTextField();
        Simpan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Batal = new javax.swing.JButton();

        // Mentutup form mhs saja
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NIM.setText("NIM");

        NAMA.setText("NAMA");

        ALAMAT.setText("ALAMAT");

        HP.setText("HP");

        KOTA.setText("KOTA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        txtNIM.setText("txtNIM");
        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });

        txtNAMA.setText("txtNAMA");

        txtALAMAT.setText("txtALAMAT");

        txtHP.setText("txtHP");

        txtKOTA.setText("txtKOTA");

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Batal.setText("Batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(ALAMAT, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(KOTA, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(HP, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(NAMA, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(NIM, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(txtNIM)
                                                        .addComponent(txtNAMA)
                                                        .addComponent(txtALAMAT, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                116, Short.MAX_VALUE)
                                                        .addComponent(txtHP)
                                                        .addComponent(txtKOTA)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(Simpan)
                                                .addGap(18, 18, 18)
                                                .addComponent(Hapus)
                                                .addGap(18, 18, 18)
                                                .addComponent(Edit)
                                                .addGap(18, 18, 18)
                                                .addComponent(Batal)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NIM, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNIM))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NAMA, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNAMA))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ALAMAT, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtALAMAT))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(HP, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHP))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(KOTA, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtKOTA))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Simpan)
                                        .addComponent(Hapus)
                                        .addComponent(Edit)
                                        .addComponent(Batal))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SimpanActionPerformed
        // Validasi: pastikan semua field diisi
        if (txtNIM.getText().isEmpty() || txtNAMA.getText().isEmpty() ||
                txtALAMAT.getText().isEmpty() || txtHP.getText().isEmpty() ||
                txtKOTA.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data belum lengkap!", "Konfirmasi",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Query INSERT untuk menambah data mahasiswa baru
        try {
            String nim = txtNIM.getText();
            String nama = txtNAMA.getText();
            String alamat = txtALAMAT.getText();
            String hp = txtHP.getText();
            String kota = txtKOTA.getText();

            String query = "INSERT INTO mhs (nim, nama, alamat, hp, kota) VALUES ('"
                    + nim + "', '" + nama + "', '" + alamat + "', '" + hp + "', '" + kota + "')";
            stmt.executeUpdate(query);

            // Refresh tabel dan bersihkan form setelah berhasil simpan
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Info",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            clearText();
            tabelmhs();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_SimpanActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HapusActionPerformed
        // Validasi: NIM harus diisi sebelum menghapus
        if (txtNIM.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data belum terpilih!", "Konfirmasi",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Konfirmasi sebelum menghapus data
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah yakin ingin menghapus data NIM: " + txtNIM.getText() + "?",
                "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            // Query DELETE berdasarkan NIM
            try {
                String nim = txtNIM.getText();
                String query = "DELETE FROM mhs WHERE nim = '" + nim + "'";
                stmt.executeUpdate(query);

                // Refresh tabel dan bersihkan form setelah berhasil hapus
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Info",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                clearText();
                tabelmhs();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_HapusActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EditActionPerformed
        // Validasi: pastikan semua field diisi sebelum update
        if (txtNIM.getText().isEmpty() || txtNAMA.getText().isEmpty() ||
                txtALAMAT.getText().isEmpty() || txtHP.getText().isEmpty() ||
                txtKOTA.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data belum terpilih!", "Konfirmasi",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Query UPDATE untuk mengubah data mahasiswa berdasarkan NIM
        try {
            String nim = txtNIM.getText();
            String nama = txtNAMA.getText();
            String alamat = txtALAMAT.getText();
            String hp = txtHP.getText();
            String kota = txtKOTA.getText();

            String query = "UPDATE mhs SET nama = '" + nama
                    + "', alamat = '" + alamat
                    + "', hp = '" + hp
                    + "', kota = '" + kota
                    + "' WHERE nim = '" + nim + "'";
            stmt.executeUpdate(query);

            // Refresh tabel dan bersihkan form setelah berhasil update
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Info",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            clearText();
            tabelmhs();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_EditActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BatalActionPerformed
        // Bersihkan semua field input dan batalkan operasi
        clearText();
    }// GEN-LAST:event_BatalActionPerformed

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNIMActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNIMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MhsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALAMAT;
    private javax.swing.JButton Batal;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel HP;
    private javax.swing.JButton Hapus;
    private javax.swing.JLabel KOTA;
    private javax.swing.JLabel NAMA;
    private javax.swing.JLabel NIM;
    private javax.swing.JButton Simpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtALAMAT;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtKOTA;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtNIM;
    // End of variables declaration//GEN-END:variables
}
