/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhirrentalwarnet;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ROG G513RM
 */
public class FrameTambahPC extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(FrameTambahPC.class.getName());

    /**
     * Creates new form FrameTambahPC
     */
    public FrameTambahPC() {
        initComponents();

        this.setLocationRelativeTo(null);

        // clean();
    }

    public void cleantxt() {
        txtHargaPC.setText("");
        txtNamaPC.setText("");
    }

    public void isitxt() {
        txtNamaPC.setText("Nama PC");
        txtHargaPC.setText("Harga PC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaPC = new javax.swing.JTextField();
        txtHargaPC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        cmbTipePC = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel5.setText("=== STARK-COMP TAMBAH PC ===");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 6);
        jPanel1.add(txtNamaPC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 6);
        jPanel1.add(txtHargaPC, gridBagConstraints);

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtDeskripsi);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 198;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        cmbTipePC.setModel(
            new javax.swing.DefaultComboBoxModel<>(new String[] {
                "REGULAR",
                "VIP",
            })
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 6);
        jPanel1.add(cmbTipePC, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnBatal.setBackground(new java.awt.Color(199, 0, 0));
        btnBatal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBatalActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 7);
        jPanel2.add(btnBatal, gridBagConstraints);

        btnSimpan.setBackground(new java.awt.Color(30, 144, 255));
        btnSimpan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSimpanActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 7);
        jPanel2.add(btnSimpan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel1.setText("Nama PC: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Harga PC:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 6);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Jenis PC:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 6);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Deskripsi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 6);
        jPanel1.add(jLabel4, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane()
        );
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            jPanel1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addContainerGap()
                )
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(
                            jPanel1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addContainerGap(
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE
                        )
                )
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    } //GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String namaPC = txtNamaPC.getText().trim();
        String txtHarga = txtHargaPC.getText().trim();
        String tipePC = cmbTipePC.getSelectedItem().toString();
        String deskripsi = txtDeskripsi.getText().trim();

        // Validasi input kosong
        if (namaPC.isEmpty() || txtHarga.isEmpty() || deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kotak wajib diisi!");
            return;
        }

        // Validasi angka untuk tarif harga
        int harga = 0;
        try {
            harga = Integer.parseInt(txtHarga);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this,
                "Tarif per jam harus berupa angka murni tanpa titik atau koma!"
            );
            return;
        }

        Connection conn = Koneksi.getKoneksi();
        try {
            // Aktifkan mode transaksi aman untuk menjamin integritas data saat pengisian kedua tabel
            conn.setAutoCommit(false);

            // Masukkan data komputer ke tabel utama (computer_id otomatis increment, status 'AVAILABLE' otomatis)
            String sqlPC =
                "INSERT INTO computer (pc_name, hourly_rate, status) VALUES (?, ?, 'AVAILABLE')";
            PreparedStatement psPC = conn.prepareStatement(
                sqlPC,
                Statement.RETURN_GENERATED_KEYS
            );
            psPC.setString(1, namaPC.toUpperCase());
            psPC.setInt(2, harga);
            psPC.executeUpdate();

            // Ambil ID komputer yang baru saja dibuat secara otomatis dari database
            ResultSet rsKeys = psPC.getGeneratedKeys();
            int generatedId = 0;
            if (rsKeys.next()) {
                generatedId = rsKeys.getInt(1);
            }

            // Masukkan deskripsi spesifikasi ke tabel terpisah computer_spec berdasarkan ID yang baru dibuat tadi
            String sqlSpec =
                "INSERT INTO computer_spec (computer_id, pc_type, description) VALUES (?, ?, ?)";
            PreparedStatement psSpec = conn.prepareStatement(sqlSpec);
            psSpec.setInt(1, generatedId);
            psSpec.setString(2, tipePC);
            psSpec.setString(3, deskripsi);
            psSpec.executeUpdate();

            // Simpan semua perubahan ke database
            conn.commit();
            conn.setAutoCommit(true);

            JOptionPane.showMessageDialog(
                this,
                "Komputer " + namaPC + " dengan status AVAILABLE berhasil ditambahkan!"
            );

            // Lakukan pembaruan data pada MainFrame secara real-time agar kotak baru langsung muncul
            for (java.awt.Window window : java.awt.Window.getWindows()) {
                if (window instanceof MainFrame) {
                    ((MainFrame) window).loadDataPC();
                }
            }
            this.dispose(); // Tutup frame input
        } catch (Exception e) {
            try {
                conn.rollback();
            } catch (SQLException ex) {}
            JOptionPane.showMessageDialog(
                this,
                "Gagal melahirkan PC baru: " + e.getMessage(),
                "SQL Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    } //GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
            new FrameTambahPC().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbTipePC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtHargaPC;
    private javax.swing.JTextField txtNamaPC;
    // End of variables declaration//GEN-END:variables
}
