/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhirrentalwarnet;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ROG G513RM
 */
public class FrameLoginMember extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(FrameLoginMember.class.getName());

    /**
     * Creates new form FrameLoginMember
     */
    public FrameLoginMember() {
        initComponents();

        this.setLocationRelativeTo(null);

        loadDataCustomer();
    }

    // Variabel penampung ID PC yang diklik dari MainFrame
    private String idPCKirim;

    // Constructor custom agar bisa menerima lemparan data ID PC
    public FrameLoginMember(String idPC) {
        initComponents();
        this.idPCKirim = idPC;
        setLocationRelativeTo(null);
        loadDataCustomer();
    }

    public void loadDataCustomer() {
        javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Member");
        model.addColumn("No HP");

        try {
            java.sql.Connection conn = Koneksi.getKoneksi();
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(
                "SELECT * FROM customer WHERE phone != 'GUEST'"
            );

            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("customer_id"),
                    rs.getString("cust_name"),
                    rs.getString("phone"),
                });
            }
            tabelCustomer.setModel(model);
        } catch (Exception e) {
            System.err.println("Gagal load tabel member: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        btnGuest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelCustomer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 550));
        setMinimumSize(new java.awt.Dimension(700, 550));
        setPreferredSize(new java.awt.Dimension(700, 550));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("=== REGISTRASI PELANGGAN PC ===");

        jLabel2.setText("Masukkan No. HP :");

        btnLogin.setBackground(new java.awt.Color(34, 139, 34));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnLoginActionPerformed(evt);
                }
            }
        );

        btnDaftar.setBackground(new java.awt.Color(218, 165, 32));
        btnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDaftarActionPerformed(evt);
                }
            }
        );

        btnGuest.setBackground(new java.awt.Color(105, 105, 105));
        btnGuest.setForeground(new java.awt.Color(255, 255, 255));
        btnGuest.setText("Guest");
        btnGuest.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGuestActionPerformed(evt);
                }
            }
        );

        tabelCustomer.setModel(
            new javax.swing.table.DefaultTableModel(
                new Object[][] {
                    { null, null, null },
                    { null, null, null },
                    { null, null, null },
                    { null, null, null },
                },
                new String[] { "Title 1", "Title 2", "Title 3" }
            ) {
                boolean[] canEdit = new boolean[] { false, false, false };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            }
        );
        tabelCustomer.addMouseListener(
            new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelCustomerMouseClicked(evt);
                }
            }
        );
        jScrollPane1.setViewportView(tabelCustomer);
        if (tabelCustomer.getColumnModel().getColumnCount() > 0) {
            tabelCustomer.getColumnModel().getColumn(0).setResizable(false);
            tabelCustomer.getColumnModel().getColumn(1).setResizable(false);
            tabelCustomer.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane()
        );
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING,
                                    false
                                )
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(
                                            txtPhone,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            121,
                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                )
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addComponent(
                                            btnLogin,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            100,
                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addPreferredGap(
                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE
                                        )
                                        .addComponent(
                                            btnDaftar,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            100,
                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addGap(50, 50, 50)
                                        .addComponent(
                                            btnGuest,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            100,
                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                )
                                .addComponent(
                                    jScrollPane1,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    0,
                                    Short.MAX_VALUE
                                )
                                .addComponent(
                                    jLabel1,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE
                                )
                        )
                        .addContainerGap(64, Short.MAX_VALUE)
                )
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(
                            jScrollPane1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            117,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addGap(15, 15, 15)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.BASELINE
                                )
                                .addComponent(jLabel2)
                                .addComponent(
                                    txtPhone,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                        )
                        .addGap(21, 21, 21)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.BASELINE
                                )
                                .addComponent(btnDaftar)
                                .addComponent(btnLogin)
                                .addComponent(btnGuest)
                        )
                        .addContainerGap(135, Short.MAX_VALUE)
                )
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String phoneCust = txtPhone.getText().trim();
        if (phoneCust.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Masukkan No HP Member terlebih dahulu!"
            );
            return;
        }

        Connection conn = Koneksi.getKoneksi();
        try {
            String sqlCek =
                "SELECT customer_id, cust_name FROM customer WHERE phone = ?";
            PreparedStatement psCek = conn.prepareStatement(sqlCek);
            psCek.setString(1, phoneCust);
            ResultSet rsCek = psCek.executeQuery();

            if (rsCek.next()) {
                int idCust = rsCek.getInt("customer_id");
                String namaCust = rsCek.getString("cust_name");

                JOptionPane.showMessageDialog(
                    this,
                    "Member Ditemukan! Selamat datang kembali, " +
                        namaCust +
                        " 🚀"
                );

                // OPER DATA: Bawa ID PC, ID Cust, Nama Cust, dan status isGuest = false ke FramePembayaran
                new FramePembayaran(
                    idPCKirim,
                    idCust,
                    namaCust,
                    false
                ).setVisible(true);
                this.dispose(); // Tutup frame login
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No HP belum terdaftar! Silakan daftar member baru atau masuk sebagai Guest. 😂",
                    "Not Found",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Error Login: " + e.getMessage()
            );
        }
    } //GEN-LAST:event_btnLoginActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
        String phoneCust = txtPhone.getText().trim();
        if (phoneCust.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Isi No HP di kotak atas dulu untuk didaftarkan! 😹"
            );
            return;
        }

        String namaBaru = JOptionPane.showInputDialog(
            this,
            "No HP belum terdaftar.\nMasukkan Nama Lengkap Member Baru:"
        );
        if (namaBaru == null || namaBaru.trim().isEmpty()) return;

        Connection conn = Koneksi.getKoneksi();
        try {
            String sqlCustomer =
                "INSERT INTO customer (cust_name, phone) VALUES (?, ?)";
            PreparedStatement psCust = conn.prepareStatement(
                sqlCustomer,
                Statement.RETURN_GENERATED_KEYS
            );
            psCust.setString(1, namaBaru);
            psCust.setString(2, phoneCust);
            psCust.executeUpdate();

            ResultSet rsCust = psCust.getGeneratedKeys();
            int idCust = 0;
            if (rsCust.next()) idCust = rsCust.getInt(1);

            JOptionPane.showMessageDialog(
                this,
                "Pendaftaran Member Sukses atas nama: " + namaBaru
            );

            // Langsung lempar ke FramePembayaran
            new FramePembayaran(idPCKirim, idCust, namaBaru, false).setVisible(
                true
            );
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Gagal Daftar: " + e.getMessage()
            );
        }
    } //GEN-LAST:event_btnDaftarActionPerformed

    private void btnGuestActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnGuestActionPerformed
        // TODO add your handling code here:
        // Lempar data khusus: ID customer diset 0, nama diset "Guest Pelanggan", status isGuest = true
        new FramePembayaran(idPCKirim, 0, "Guest Pelanggan", true).setVisible(
            true
        );
        this.dispose();
    } //GEN-LAST:event_btnGuestActionPerformed

    private void tabelCustomerMouseClicked(java.awt.event.MouseEvent evt) {
        //GEN-FIRST:event_tabelCustomerMouseClicked
        // TODO add your handling code here:
        int row = tabelCustomer.getSelectedRow();
        if (row != -1) {
            String phone = tabelCustomer.getValueAt(row, 2).toString();
            txtPhone.setText(phone); // Auto-fill ke textfield No HP! 🚀
        }
    } //GEN-LAST:event_tabelCustomerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
            new FrameLoginMember().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnGuest;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelCustomer;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
