/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhirrentalwarnet;

import javax.swing.JOptionPane;

/**
 *
 * @author ROG G513RM
 */
public class FramePembayaran extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(FramePembayaran.class.getName());

    /**
     * Creates new form FramePembayaran
     */
    public FramePembayaran() {
        initComponents();

        this.setLocationRelativeTo(null);

        initComboListener();
    }

    private void initComboListener() {
        cmbPaket.removeAllItems();
        // Item dropdown ngikut harga PC (VIP 8rb, Reg 5rb)
        cmbPaket.addItem("Argo (Bayar Belakangan)");
        cmbPaket.addItem("Paket 1 Jam (Rp " + (tarifPerJam * 1) + ")");
        cmbPaket.addItem("Paket 3 Jam (Rp " + ((tarifPerJam * 3) - 3000) + ")");
        cmbPaket.addItem("Paket 5 Jam (Rp " + ((tarifPerJam * 5) - 5000) + ")");

        cmbPaket.addActionListener(e -> {
            if (cmbPaket.getSelectedItem() == null) return;
            String selected = cmbPaket.getSelectedItem().toString();

            if (selected.startsWith("Argo")) {
                isModeArgo = true;
                totalBiaya = 0;
                durasiMenit = 0;
                txtUangBayar.setText("0");
                txtUangBayar.setEnabled(false);
                lblTotalTagihan.setText("Rp 0 (Argo)");
            } else {
                isModeArgo = false;
                txtUangBayar.setEnabled(true);
                txtUangBayar.setText("");

                // Logika hitung ulang tagihan sesuai paket yang dipilih (Bug fix poin 4 lo!)
                if (selected.contains("1 Jam")) {
                    durasiMenit = 60;
                    totalBiaya = tarifPerJam * 1;
                } else if (selected.contains("3 Jam")) {
                    durasiMenit = 180;
                    totalBiaya = (tarifPerJam * 3) - 3000;
                } else if (selected.contains("5 Jam")) {
                    durasiMenit = 300;
                    totalBiaya = (tarifPerJam * 5) - 5000;
                }
                lblTotalTagihan.setText("Rp " + totalBiaya);
            }
        });
    }

    // 1. Tambahkan variabel penampung gaib di paling atas kelas
    private String idPC;
    private int idCustomer;
    private String namaCustomer;
    private boolean isGuest;
    private long totalBiaya = 0;
    private int durasiMenit = 0;
    private boolean isModeArgo = false;
    private int tarifPerJam = 5000; // Harga default

    // 2. Pasang Constructor Kustom yang menerima 4 parameter (BIAR KODE LOGIN GA ERROR)
    public FramePembayaran(
        String idPC,
        int idCust,
        String namaCust,
        boolean isGuest
    ) {
        initComponents();
        this.idPC = idPC;
        this.idCustomer = idCust;
        this.namaCustomer = namaCust;
        this.isGuest = isGuest;
        setLocationRelativeTo(null);

        // Ambil tarif per jam asli dari database berdasarkan PC VIP/Regular yang diklik
        try {
            java.sql.Connection c = Koneksi.getKoneksi();
            java.sql.PreparedStatement ps = c.prepareStatement(
                "SELECT hourly_rate FROM computer WHERE computer_id = ?"
            );
            ps.setString(1, idPC);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                this.tarifPerJam = rs.getInt("hourly_rate");
            }
        } catch (Exception e) {
            System.out.println("Gagal ambil tarif: " + e.getMessage());
        }

        String tipeUser = isGuest ? " (Guest)" : " (Member)";
        lblInfoUser.setText(
            "PC: " + idPC + " | Pelanggan: " + namaCustomer + tipeUser
        );

        // MAN_TRA UTAMA DIPANGGIL DISINI BIAR COMBOBOX-NYA HIDUP! 🚀
        initComboListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        lblInfoUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPaket = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbMetodeBayar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblTotalTagihan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUangBayar = new javax.swing.JTextField();
        btnSimpanBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 550));
        setMinimumSize(new java.awt.Dimension(700, 550));
        setPreferredSize(new java.awt.Dimension(700, 550));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("=== MENU BILLING & PEMBAYARAN ===");

        lblInfoUser.setText("jLabel2");

        jLabel3.setText("Pilih Jenis Paket :");

        cmbPaket.setModel(
            new javax.swing.DefaultComboBoxModel<>(new String[] {
                "Argo (Bayar Belakangan)",
                "Paket 1 Jam (Rp 5.000)",
                "Paket 3 Jam (Rp 12.000)",
                "Paket 5 Jam (Rp 18.000)",
            })
        );

        jLabel2.setText("Metode Pembayaran :");

        cmbMetodeBayar.setModel(
            new javax.swing.DefaultComboBoxModel<>(new String[] {
                "Cash",
                "QRIS",
                "Transfer Bank",
            })
        );

        jLabel4.setText("Total Tagihan :");

        lblTotalTagihan.setText("Rp 0");

        jLabel5.setText("Uang Dibayar :");

        btnSimpanBayar.setBackground(new java.awt.Color(46, 139, 87));
        btnSimpanBayar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSimpanBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanBayar.setText("Bayar");
        btnSimpanBayar.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSimpanBayarActionPerformed(evt);
                }
            }
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane()
        );
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING,
                                    false
                                )
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addGroup(
                                            layout
                                                .createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                                    false
                                                )
                                                .addComponent(
                                                    jLabel5,
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE
                                                )
                                                .addComponent(
                                                    jLabel4,
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE
                                                )
                                        )
                                        .addGap(18, 18, 18)
                                        .addGroup(
                                            layout
                                                .createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    false
                                                )
                                                .addComponent(
                                                    txtUangBayar,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    71,
                                                    Short.MAX_VALUE
                                                )
                                                .addComponent(
                                                    lblTotalTagihan,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE
                                                )
                                        )
                                )
                                .addComponent(
                                    btnSimpanBayar,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE
                                )
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addGroup(
                                            layout
                                                .createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                                    false
                                                )
                                                .addComponent(
                                                    lblInfoUser,
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE
                                                )
                                                .addComponent(
                                                    jLabel2,
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE
                                                )
                                                .addComponent(
                                                    jLabel3,
                                                    javax.swing.GroupLayout.Alignment.LEADING
                                                )
                                        )
                                        .addGap(18, 18, 18)
                                        .addGroup(
                                            layout
                                                .createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    false
                                                )
                                                .addComponent(
                                                    cmbPaket,
                                                    0,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE
                                                )
                                                .addComponent(
                                                    cmbMetodeBayar,
                                                    0,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE
                                                )
                                        )
                                )
                                .addComponent(
                                    jLabel1,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE
                                )
                        )
                        .addContainerGap(91, Short.MAX_VALUE)
                )
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoUser)
                        .addGap(18, 18, 18)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.BASELINE
                                )
                                .addComponent(jLabel3)
                                .addComponent(
                                    cmbPaket,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                        )
                        .addGap(21, 21, 21)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(jLabel2)
                                .addComponent(
                                    cmbMetodeBayar,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                        )
                        .addGap(18, 18, 18)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.BASELINE
                                )
                                .addComponent(jLabel4)
                                .addComponent(lblTotalTagihan)
                        )
                        .addGap(18, 18, 18)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.BASELINE
                                )
                                .addComponent(jLabel5)
                                .addComponent(
                                    txtUangBayar,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                        )
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpanBayar)
                        .addContainerGap(61, Short.MAX_VALUE)
                )
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btnSimpanBayarActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnSimpanBayarActionPerformed
        // TODO add your handling code here:
        String metodeBayar = cmbMetodeBayar.getSelectedItem().toString();
        long uangBayar = 0;
        long kembalian = 0;

        // 1. Validasi duit kasir super ketat untuk mode Paket (Prabayar)
        if (!isModeArgo) {
            String txtUang = txtUangBayar.getText().trim();
            if (txtUang.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this,
                    "Isi nominal duitnya dulu!"
                );
                return;
            }
            try {
                uangBayar = Long.parseLong(txtUang);
                if (uangBayar < totalBiaya) {
                    JOptionPane.showMessageDialog(
                        this,
                        "Duit kurang Rp " +
                            (totalBiaya - uangBayar) +
                            "! Transaksi BATAL.",
                        "Warning",
                        JOptionPane.ERROR_MESSAGE
                    );
                    return; // STOP EKSEKUSI! Gak boleh masuk DB!
                }
                kembalian = uangBayar - totalBiaya;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Input harus angka!");
                return;
            }
        }

        java.sql.Connection conn = Koneksi.getKoneksi();
        try {
            conn.setAutoCommit(false); // Kunci transaksi database biar aman dari crash (ACID)

            // 2. Jika pelanggan masuk sebagai GUEST, buatkan record otomatis di tabel customer
            if (isGuest) {
                String sqlGuest =
                    "INSERT INTO customer (cust_name, phone) VALUES (?, 'GUEST')";
                java.sql.PreparedStatement psG = conn.prepareStatement(
                    sqlGuest,
                    java.sql.Statement.RETURN_GENERATED_KEYS
                );
                psG.setString(1, namaCustomer);
                psG.executeUpdate();
                java.sql.ResultSet rsG = psG.getGeneratedKeys();
                if (rsG.next()) idCustomer = rsG.getInt(1);
            }

            String idTrans = "TRX-" + System.currentTimeMillis();
            String sqlTransaksi;
            java.sql.PreparedStatement psTrans;

            // 3. Insert data transaksi dinamis berdasarkan pilihan dropdown paket
            if (isModeArgo) {
                sqlTransaksi =
                    "INSERT INTO rental_tran (tran_id, computer_id, customer_id, start_time) VALUES (?, ?, ?, NOW())";
                psTrans = conn.prepareStatement(sqlTransaksi);
                psTrans.setString(1, idTrans);
                psTrans.setString(2, idPC);
                psTrans.setInt(3, idCustomer);
            } else {
                sqlTransaksi =
                    "INSERT INTO rental_tran (tran_id, computer_id, customer_id, start_time, duration_minutes, total_cost) VALUES (?, ?, ?, NOW(), ?, ?)";
                psTrans = conn.prepareStatement(sqlTransaksi);
                psTrans.setString(1, idTrans);
                psTrans.setString(2, idPC);
                psTrans.setInt(3, idCustomer);
                psTrans.setInt(4, durasiMenit);
                psTrans.setLong(5, totalBiaya);
            }
            psTrans.executeUpdate();

            // 4. Update status PC di MySQL menjadi OCCUPIED
            String sqlUpdatePC =
                "UPDATE computer SET status = 'OCCUPIED' WHERE computer_id = ?";
            java.sql.PreparedStatement psPC = conn.prepareStatement(
                sqlUpdatePC
            );
            psPC.setString(1, idPC);
            psPC.executeUpdate();

            conn.commit(); // Simpan permanen ke MySQL bersamaan
            conn.setAutoCommit(true);

            // 5. Buka FrameStruk untuk memamerkan Nota Lunas Digital buatan lo!
            String paketTxt = cmbPaket.getSelectedItem().toString();
            new FrameStruk(
                idTrans,
                namaCustomer,
                paketTxt,
                totalBiaya,
                uangBayar,
                kembalian,
                metodeBayar
            ).setVisible(true);

            // 6. Sihir pemaksa refresh untuk meng-update warna border MainFrame secara real-time
            for (java.awt.Window window : java.awt.Window.getWindows()) {
                if (window instanceof MainFrame) {
                    ((MainFrame) window).loadDataPC();
                }
            }
            this.dispose(); // Hancurkan frame pembayaran karena urusan duit kasir udah beres
        } catch (Exception e) {
            try {
                conn.rollback();
            } catch (java.sql.SQLException ex) {}
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal memproses transaksi: " + e.getMessage(),
                "Database Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    } //GEN-LAST:event_btnSimpanBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
            new FramePembayaran().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanBayar;
    private javax.swing.JComboBox<String> cmbMetodeBayar;
    private javax.swing.JComboBox<String> cmbPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblInfoUser;
    private javax.swing.JLabel lblTotalTagihan;
    private javax.swing.JTextField txtUangBayar;
    // End of variables declaration//GEN-END:variables
}
