/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhirrentalwarnet;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Duration;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG G513RM
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        loadDataPC();
    }

    public void loadDataPC() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PC");
        model.addColumn("Nama PC");
        model.addColumn("Tarif / Jam");
        model.addColumn("Status");

        try {
            Connection conn = Koneksi.getKoneksi();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM computer");

            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("computer_id"),
                    rs.getString("pc_name"),
                    "Rp " + rs.getInt("hourly_rate"),
                    rs.getString("status"),
                });
            }

            tabelPC.setModel(model); // Pastikan nama variabel JTable lo adalah tabelPC
        } catch (Exception e) {
            System.err.println("Gagal load tabel: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPC = new javax.swing.JTable();
        buttonCheckIn = new javax.swing.JButton();
        buttonCheckOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelPC.setModel(
            new javax.swing.table.DefaultTableModel(
                new Object[][] {
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null },
                },
                new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }
            )
        );
        jScrollPane1.setViewportView(tabelPC);

        buttonCheckIn.setText("Check In");
        buttonCheckIn.addActionListener(
            new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    buttonCheckInActionPerformed(evt);
                }
            }
        );

        buttonCheckOut.setText("CheckOut");
        buttonCheckOut.addActionListener(
            new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    buttonCheckOutActionPerformed(evt);
                }
            }
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane()
        );
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING,
                                    false
                                )
                                .addComponent(
                                    jScrollPane1,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    375,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addComponent(
                                            buttonCheckIn,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            175,
                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addPreferredGap(
                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                        )
                                        .addComponent(
                                            buttonCheckOut,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE
                                        )
                                )
                        )
                        .addContainerGap(148, Short.MAX_VALUE)
                )
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(
                            jScrollPane1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            275,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED
                        )
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING,
                                    false
                                )
                                .addComponent(
                                    buttonCheckIn,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    30,
                                    Short.MAX_VALUE
                                )
                                .addComponent(
                                    buttonCheckOut,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE
                                )
                        )
                        .addContainerGap(92, Short.MAX_VALUE)
                )
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void buttonCheckInActionPerformed(ActionEvent evt) {
        //GEN-FIRST:event_buttonCheckInActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelPC.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Pilih PC di tabel terlebih dahulu!"
            );
            return;
        }

        String idPC = tabelPC.getValueAt(selectedRow, 0).toString();
        String status = tabelPC.getValueAt(selectedRow, 3).toString();

        if (status.equals("OCCUPIED")) {
            JOptionPane.showMessageDialog(
                this,
                "PC ini sedang dipakai!"
            );
            return;
        }

        // 1. DROPDOWN COMBOBOX UNTUK PILIH JENIS BILLING
        String[] opsiBilling = {
            "Argo (Bayar Belakangan)",
            "Paket 1 Jam (Rp 5.000)",
            "Paket 3 Jam (Rp 12.000)",
            "Paket 5 Jam (Rp 18.000)",
        };
        String pilihan = (String) JOptionPane.showInputDialog(
            this,
            "Pilih Jenis Billing / Paket Semu:",
            "Menu Registrasi PC",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opsiBilling,
            opsiBilling[0]
        );

        if (pilihan == null) return; // Batal jika klik cancel

        int durasiMenit = 0;
        long totalBiaya = 0;
        boolean isArgo = false;

        // Tentukan logika berdasarkan ComboBox yang dipilih
        if (pilihan.equals(opsiBilling[0])) {
            isArgo = true; // Mode Argo Aktif!
        } else if (pilihan.equals(opsiBilling[1])) {
            durasiMenit = 60;
            totalBiaya = 5000;
        } else if (pilihan.equals(opsiBilling[2])) {
            durasiMenit = 180;
            totalBiaya = 12000;
        } else if (pilihan.equals(opsiBilling[3])) {
            durasiMenit = 300;
            totalBiaya = 18000;
        }

        // 2. INPUT DATA CUSTOMER
        String namaCust = JOptionPane.showInputDialog(
            this,
            "Masukkan Nama Pelanggan:"
        );
        if (namaCust == null || namaCust.trim().isEmpty()) return;
        String phoneCust = JOptionPane.showInputDialog(
            this,
            "Masukkan No HP Pelanggan:"
        );
        if (phoneCust == null || phoneCust.trim().isEmpty()) return;

        long uangBayar = 0;
        long kembalian = 0;

        // 3. VALIDASI DUIT DI AWAL HANYA JIKA MEMILIH PAKET
        if (!isArgo) {
            String inputBayar = JOptionPane.showInputDialog(
                this,
                "Total Tagihan Paket: Rp " +
                    totalBiaya +
                    "\nMasukkan Uang Cash:"
            );
            if (inputBayar == null || inputBayar.trim().isEmpty()) return;

            uangBayar = Long.parseLong(inputBayar);
            if (uangBayar < totalBiaya) {
                JOptionPane.showMessageDialog(
                    this,
                    "Duit kurang, Cik! Gak ada utang paket ya. 😹",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            kembalian = uangBayar - totalBiaya;
        }

        // 4. EKSEKUSI KE DATABASE SQL
        Connection conn = Koneksi.getKoneksi();
        try {
            conn.setAutoCommit(false);

            // A. Insert Customer
            String sqlCustomer =
                "INSERT INTO customer (cust_name, phone) VALUES (?, ?)";
            PreparedStatement psCust = conn.prepareStatement(
                sqlCustomer,
                Statement.RETURN_GENERATED_KEYS
            );
            psCust.setString(1, namaCust);
            psCust.setString(2, phoneCust);
            psCust.executeUpdate();

            ResultSet rsCust = psCust.getGeneratedKeys();
            int idCust = 0;
            if (rsCust.next()) idCust = rsCust.getInt(1);

            String idTrans = "TRX-" + System.currentTimeMillis();

            // B. Insert Transaksi Dinamis
            String sqlTransaksi;
            PreparedStatement psTrans;

            if (isArgo) {
                // Jika Argo, biarkan duration_minutes dan total_cost bernilai NULL di awal
                sqlTransaksi =
                    "INSERT INTO rental_tran (tran_id, computer_id, customer_id, start_time) VALUES (?, ?, ?, NOW())";
                psTrans = conn.prepareStatement(sqlTransaksi);
                psTrans.setString(1, idTrans);
                psTrans.setString(2, idPC);
                psTrans.setInt(3, idCust);
            } else {
                // Jika Paket, langsung masukkan durasi dan biayanya karena sudah LUNAS
                sqlTransaksi =
                    "INSERT INTO rental_tran (tran_id, computer_id, customer_id, start_time, duration_minutes, total_cost) VALUES (?, ?, ?, NOW(), ?, ?)";
                psTrans = conn.prepareStatement(sqlTransaksi);
                psTrans.setString(1, idTrans);
                psTrans.setString(2, idPC);
                psTrans.setInt(3, idCust);
                psTrans.setInt(4, durasiMenit);
                psTrans.setLong(5, totalBiaya);
            }
            psTrans.executeUpdate();

            // C. Update Status PC jadi OCCUPIED
            String sqlUpdatePC =
                "UPDATE computer SET status = 'OCCUPIED' WHERE computer_id = ?";
            PreparedStatement psPC = conn.prepareStatement(sqlUpdatePC);
            psPC.setString(1, idPC);
            psPC.executeUpdate();

            conn.commit();
            conn.setAutoCommit(true);

            // Tampilkan Pesan Sukses Sesuai Jenis Metode
            if (isArgo) {
                JOptionPane.showMessageDialog(
                    this,
                    "Check In ARGO Berhasil! Billing waktu mulai berjalan... ⏱️"
                );
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "=== NOTA PAKET LUNAS ===" +
                        "\nID Transaksi : " +
                        idTrans +
                        "\nPilihan      : " +
                        pilihan +
                        "\nKembalian    : Rp " +
                        kembalian +
                        "\n\nPC " +
                        idPC +
                        " Aktif! 🚀"
                );
            }

            loadDataPC(); // Refresh tabel UI
        } catch (Exception e) {
            try {
                conn.rollback();
            } catch (Exception ex) {}
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    } //GEN-LAST:event_buttonCheckInActionPerformed

    private void buttonCheckOutActionPerformed(ActionEvent evt) {
        //GEN-FIRST:event_buttonCheckOutActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelPC.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Pilih PC yang mau di-CheckOut! 😹"
            );
            return;
        }

        String idPC = tabelPC.getValueAt(selectedRow, 0).toString();
        String status = tabelPC.getValueAt(selectedRow, 3).toString();

        if (!status.equals("OCCUPIED")) {
            JOptionPane.showMessageDialog(
                this,
                "PC ini emang lagi kosong, Bos! 😂"
            );
            return;
        }

        Connection conn = Koneksi.getKoneksi();
        try {
            // Cek dulu, ini sesi Argo atau Paket?
            String sqlCari =
                "SELECT r.tran_id, r.start_time, r.total_cost, c.hourly_rate FROM rental_tran r " +
                "JOIN computer c ON r.computer_id = c.computer_id " +
                "WHERE r.computer_id = ? AND r.end_time IS NULL";
            PreparedStatement psCari = conn.prepareStatement(sqlCari);
            psCari.setString(1, idPC);
            ResultSet rs = psCari.executeQuery();

            if (rs.next()) {
                String idTrans = rs.getString("tran_id");
                Timestamp startTime = rs.getTimestamp("start_time");
                long totalCostExist = rs.getLong("total_cost");
                boolean isPaket = !rs.wasNull(); // Kalo total_cost gak kosong, berarti Paket
                int hourlyRate = rs.getInt("hourly_rate");

                conn.setAutoCommit(false);

                if (isPaket) {
                    // LOGIKA PAKET: Cuma numpang lewat buat update jam selesai aja
                    int konfirm = JOptionPane.showConfirmDialog(
                        this,
                        "Pelanggan PAKET sudah selesai?\nKosongkan PC " +
                            idPC +
                            "?",
                        "CheckOut Paket",
                        JOptionPane.YES_NO_OPTION
                    );
                    if (konfirm != JOptionPane.YES_OPTION) return;

                    String sqlUpTrans =
                        "UPDATE rental_tran SET end_time = NOW() WHERE tran_id = ?";
                    PreparedStatement psUp = conn.prepareStatement(sqlUpTrans);
                    psUp.setString(1, idTrans);
                    psUp.executeUpdate();
                } else {
                    // LOGIKA ARGO: Hitung durasi dan malak duit pembeli
                    Timestamp endTime = new Timestamp(
                        System.currentTimeMillis()
                    );
                    long durationMinutes = Duration.between(
                        startTime.toLocalDateTime(),
                        endTime.toLocalDateTime()
                    ).toMinutes();
                    if (durationMinutes <= 0) durationMinutes = 1;

                    long hitungBiaya = (durationMinutes * hourlyRate) / 60;

                    JOptionPane.showMessageDialog(
                        this,
                        "--- ARGO SELESAI ---\nDurasi: " +
                            durationMinutes +
                            " Menit\nTagihan: Rp " +
                            hitungBiaya
                    );

                    String inputBayar = JOptionPane.showInputDialog(
                        this,
                        "Masukkan Uang Pembayaran:"
                    );
                    if (
                        inputBayar == null || inputBayar.trim().isEmpty()
                    ) return;

                    long uangBayar = Long.parseLong(inputBayar);
                    if (uangBayar < hitungBiaya) {
                        JOptionPane.showMessageDialog(
                            this,
                            "Duit kurang! Jangan kabur. 😹"
                        );
                        return;
                    }

                    // Update durasi & biaya ke SQL
                    String sqlUpTrans =
                        "UPDATE rental_tran SET end_time = NOW(), duration_minutes = ?, total_cost = ? WHERE tran_id = ?";
                    PreparedStatement psUp = conn.prepareStatement(sqlUpTrans);
                    psUp.setLong(1, durationMinutes);
                    psUp.setLong(2, hitungBiaya);
                    psUp.setString(3, idTrans);
                    psUp.executeUpdate();

                    JOptionPane.showMessageDialog(
                        this,
                        "Lunas! Kembalian: Rp " + (uangBayar - hitungBiaya)
                    );
                }

                // KEMBALIKAN PC JADI AVAILABLE (Berlaku buat Argo & Paket)
                String sqlUpPC =
                    "UPDATE computer SET status = 'AVAILABLE' WHERE computer_id = ?";
                PreparedStatement psPC = conn.prepareStatement(sqlUpPC);
                psPC.setString(1, idPC);
                psPC.executeUpdate();

                conn.commit();
                conn.setAutoCommit(true);

                loadDataPC(); // Refresh tabel layar
            }
        } catch (Exception e) {
            try {
                conn.rollback();
            } catch (Exception ex) {}
            JOptionPane.showMessageDialog(
                this,
                "Error CheckOut: " + e.getMessage()
            );
        }
    } //GEN-LAST:event_buttonCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCheckIn;
    private javax.swing.JButton buttonCheckOut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPC;
    // End of variables declaration//GEN-END:variables
}
