/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhirrentalwarnet;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG G513RM
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        loadDataPC();
    }

    public void loadDataPC() {
        // 1. Desain kolom tabel sesuai rancangan kita kemarin
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PC");
        model.addColumn("Nama PC");
        model.addColumn("Tarif / Jam");
        model.addColumn("Status");

        try {
            // 2. Panggil class Koneksi
            Connection conn = Koneksi.getKoneksi();
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM computer"; // Ambil data dari tabel computer
            ResultSet rs = stmt.executeQuery(sql);

            // 3. Masukkan datanya baris demi baris
            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("computer_id"),
                    rs.getString("pc_name"),
                    "Rp " + rs.getInt("hourly_rate"),
                    rs.getString("status"),
                });
            }

            // 4. Set modelnya ke JTable lo.
            // PENTING: Pastikan nama variabel JTable lo di kanan bawah NetBeans adalah "jTable1" (atau sesuaikan)
            tabelPC.setModel(model);
            System.out.println("Data PC Sukses Ditampilkan, Cik! 🚀");
        } catch (Exception e) {
            System.err.println("Gagal memuat data tabel: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPC = new javax.swing.JTable();
        buttonCheckIn = new javax.swing.JButton();
        buttonCheckOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelPC.setModel(
            new javax.swing.table.DefaultTableModel(
                new Object[][] {
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null },
                },
                new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }
            )
        );
        jScrollPane1.setViewportView(tabelPC);

        buttonCheckIn.setText("Check In");
        buttonCheckIn.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonCheckInActionPerformed(evt);
                }
            }
        );

        buttonCheckOut.setText("CheckOut");
        buttonCheckOut.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonCheckOutActionPerformed(evt);
                }
            }
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane()
        );
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING,
                                    false
                                )
                                .addComponent(
                                    jScrollPane1,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    375,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addComponent(
                                            buttonCheckIn,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            175,
                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addPreferredGap(
                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                        )
                                        .addComponent(
                                            buttonCheckOut,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE
                                        )
                                )
                        )
                        .addContainerGap(148, Short.MAX_VALUE)
                )
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(
                            jScrollPane1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            275,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED
                        )
                        .addGroup(
                            layout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING,
                                    false
                                )
                                .addComponent(
                                    buttonCheckIn,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    30,
                                    Short.MAX_VALUE
                                )
                                .addComponent(
                                    buttonCheckOut,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE
                                )
                        )
                        .addContainerGap(92, Short.MAX_VALUE)
                )
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void buttonCheckInActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_buttonCheckInActionPerformed
        // TODO add your handling code here:
        // 1. Ambil baris tabel yang sedang dipilih/diklik oleh user
        int selectedRow = tabelPC.getSelectedRow();

        // Validasi: Pastikan user sudah milih PC di tabel sebelum klik tombol
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pilih PC di tabel dulu, Bro! 😹",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 2. Ambil data ID PC dan Status dari baris tabel yang dipilih
        String idPC = tabelPC.getValueAt(selectedRow, 0).toString();
        String status = tabelPC.getValueAt(selectedRow, 3).toString();

        // Validasi: Kalau statusnya sudah OCCUPIED, gak boleh disewa lagi!
        if (status.equals("OCCUPIED")) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "PC ini lagi dipake main, cari yang kosong! 😂",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // 3. Munculkan pop-up input data pelanggan
        String namaCust = javax.swing.JOptionPane.showInputDialog(
            this,
            "Masukkan Nama Pelanggan:"
        );
        if (namaCust == null || namaCust.trim().isEmpty()) return; // Batalkan jika input kosong

        String phoneCust = javax.swing.JOptionPane.showInputDialog(
            this,
            "Masukkan No HP Pelanggan:"
        );
        if (phoneCust == null || phoneCust.trim().isEmpty()) return;

        // 4. Proses Eksekusi ke Database SQL
        java.sql.Connection conn = Koneksi.getKoneksi();
        try {
            // Matikan auto-commit untuk mengaktifkan fitur ACID Transaction (Biar dosen makin bangga! 😎)
            conn.setAutoCommit(false);

            // A. Insert data pelanggan baru ke tabel customer
            String sqlCustomer =
                "INSERT INTO customer (cust_name, phone) VALUES (?, ?)";
            java.sql.PreparedStatement psCust = conn.prepareStatement(
                sqlCustomer,
                java.sql.Statement.RETURN_GENERATED_KEYS
            );
            psCust.setString(1, namaCust);
            psCust.setString(2, phoneCust);
            psCust.executeUpdate();

            // Ambil ID Customer yang barusan digenerate otomatis oleh SQL
            java.sql.ResultSet rsCust = psCust.getGeneratedKeys();
            int idCust = 0;
            if (rsCust.next()) {
                idCust = rsCust.getInt(1);
            }

            // B. Bikin nomor nota transaksi otomatis (Contoh: TRX-WaktuSekarang)
            String idTrans = "TRX-" + System.currentTimeMillis();

            // C. Insert data ke tabel transaksi rental_tran (start_time pake NOW() bawaan SQL)
            String sqlTransaksi =
                "INSERT INTO rental_tran (tran_id, computer_id, customer_id, start_time) VALUES (?, ?, ?, NOW())";
            java.sql.PreparedStatement psTrans = conn.prepareStatement(
                sqlTransaksi
            );
            psTrans.setString(1, idTrans);
            psTrans.setString(2, idPC);
            psTrans.setInt(3, idCust);
            psTrans.executeUpdate();

            // D. Update status PC di tabel computer menjadi 'OCCUPIED'
            String sqlUpdatePC =
                "UPDATE computer SET status = 'OCCUPIED' WHERE computer_id = ?";
            java.sql.PreparedStatement psPC = conn.prepareStatement(
                sqlUpdatePC
            );
            psPC.setString(1, idPC);
            psPC.executeUpdate();

            // Jika semua query sukses tanpa error, commit datanya secara permanen
            conn.commit();
            conn.setAutoCommit(true);

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Check In Berhasil! PC " + idPC + " resmi aktif. 🚀"
            );

            // 5. Refresh isi JTable biar statusnya langsung berubah jadi OCCUPIED secara real-time
            loadDataPC();
        } catch (Exception e) {
            try {
                conn.rollback(); // Batalkan semua query jika di tengah jalan ada yang error
            } catch (java.sql.SQLException ex) {
                System.err.println("Rollback gagal: " + ex.getMessage());
            }
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Transaksi Gagal: " + e.getMessage(),
                "Error Database",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    } //GEN-LAST:event_buttonCheckInActionPerformed

    private void buttonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_buttonCheckOutActionPerformed
        // TODO add your handling code here:
        // 1. Ambil baris tabel yang dipilih
        int selectedRow = tabelPC.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pilih PC yang mau di-CheckOut dulu, Bro! 😹",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String idPC = tabelPC.getValueAt(selectedRow, 0).toString();
        String status = tabelPC.getValueAt(selectedRow, 3).toString();

        // Validasi: Pastikan PC yang dipilih memang lagi dipakai
        if (!status.equals("OCCUPIED")) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "PC ini emang lagi nganggur, gak bisa di-CheckOut! 😂",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        java.sql.Connection conn = Koneksi.getKoneksi();
        try {
            // 2. Ambil data start_time dan tarif_per_jam dari database berdasarkan sesi aktif
            String sqlCariSesi =
                "SELECT r.tran_id, r.start_time, c.hourly_rate FROM rental_tran r " +
                "JOIN computer c ON r.computer_id = c.computer_id " +
                "WHERE r.computer_id = ? AND r.end_time IS NULL";

            java.sql.PreparedStatement psCari = conn.prepareStatement(
                sqlCariSesi
            );
            psCari.setString(1, idPC);
            java.sql.ResultSet rsSesi = psCari.executeQuery();

            if (rsSesi.next()) {
                String idTrans = rsSesi.getString("tran_id");
                java.sql.Timestamp startTime = rsSesi.getTimestamp(
                    "start_time"
                );
                int hourlyRate = rsSesi.getInt("hourly_rate");

                // Waktu check-out = waktu sekarang
                java.sql.Timestamp endTime = new java.sql.Timestamp(
                    System.currentTimeMillis()
                );

                // 3. Hitung selisih waktu dalam menit menggunakan java.time
                java.time.LocalDateTime startLDT = startTime.toLocalDateTime();
                java.time.LocalDateTime endLDT = endTime.toLocalDateTime();
                long durationMinutes = java.time.Duration.between(
                    startLDT,
                    endLDT
                ).toMinutes();

                // Pengaman minimal billing (Jika baru main < 1 menit, anggap aja 1 menit biar gak 0 rupiah)
                if (durationMinutes <= 0) durationMinutes = 1;

                // 4. Hitung total biaya (Tarif per menit = hourlyRate / 60)
                long totalCost = (durationMinutes * hourlyRate) / 60;

                // Tampilkan info billing ke kasir
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "--- rincian billing ---" +
                        "\nDurasi Bermain: " +
                        durationMinutes +
                        " Menit" +
                        "\nTotal Tagihan: Rp " +
                        totalCost,
                    "Billing Terhitung",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );

                // 5. Minta input uang pembayaran dari kasir
                String inputBayar = javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Total: Rp " + totalCost + "\nMasukkan Uang Pembayaran:"
                );
                if (inputBayar == null || inputBayar.trim().isEmpty()) return;

                long uangBayar = Long.parseLong(inputBayar);

                // Validasi uang cukup/kurang
                if (uangBayar < totalCost) {
                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Uang kurang, Cik! Gak bisa diskon otomatis. 😹",
                        "Transaksi Gagal",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }

                long kembalian = uangBayar - totalCost;

                // 6. UPDATE DATA KE DATABASE (Gunakan ACID Transaction lagi)
                conn.setAutoCommit(false);

                // A. Update tabel rental_tran (isi end_time, duration, total_cost)
                String sqlUpdateTrans =
                    "UPDATE rental_tran SET end_time = NOW(), duration_minutes = ?, total_cost = ? WHERE tran_id = ?";
                java.sql.PreparedStatement psUpTrans = conn.prepareStatement(
                    sqlUpdateTrans
                );
                psUpTrans.setLong(1, durationMinutes);
                psUpTrans.setLong(2, totalCost);
                psUpTrans.setString(3, idTrans);
                psUpTrans.executeUpdate();

                // B. Kembalikan status PC menjadi 'AVAILABLE'
                String sqlUpdatePC =
                    "UPDATE computer SET status = 'AVAILABLE' WHERE computer_id = ?";
                java.sql.PreparedStatement psUpPC = conn.prepareStatement(
                    sqlUpdatePC
                );
                psUpPC.setString(1, idPC);
                psUpPC.executeUpdate();

                conn.commit();
                conn.setAutoCommit(true);

                // 7. Cetak Struk Kembalian ke User
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "=== STRUK PEMBAYARAN SUKSES ===" +
                        "\nID Transaksi: " +
                        idTrans +
                        "\nTotal Biaya: Rp " +
                        totalCost +
                        "\nUang Bayar : Rp " +
                        uangBayar +
                        "\nKembalian  : Rp " +
                        kembalian +
                        "\n\nStatus PC kembali AVAILABLE! 🚀"
                );

                // 8. Refresh tabel
                loadDataPC();
            }
        } catch (Exception e) {
            try {
                conn.rollback();
            } catch (Exception ex) {}
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal CheckOut: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    } //GEN-LAST:event_buttonCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCheckIn;
    private javax.swing.JButton buttonCheckOut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPC;
    // End of variables declaration//GEN-END:variables
}
