/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas11;

/**
 *
 * @author ROG G513RM
 */
public class FrameMain extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMain.class.getName());

    /**
     * Creates new form MainFrame
     */
    public FrameMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MUtama = new javax.swing.JMenu();
        Login = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnkeluar = new javax.swing.JMenuItem();
        MMaster = new javax.swing.JMenu();
        mnPenduduk = new javax.swing.JMenuItem();
        MnMahasiswa = new javax.swing.JMenuItem();
        MTransaksi = new javax.swing.JMenu();
        itemBarang = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MLaporan = new javax.swing.JMenu();
        MKOnfigurasi = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MUtama.setText("Menu Utama");

        Login.setLabel("Login");
        MUtama.add(Login);

        jMenuItem1.setLabel("Logout");
        MUtama.add(jMenuItem1);
        MUtama.add(jSeparator1);

        mnkeluar.setText("Keluar");
        mnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnkeluarActionPerformed(evt);
            }
        });
        MUtama.add(mnkeluar);

        jMenuBar1.add(MUtama);

        MMaster.setLabel("Master");

        mnPenduduk.setText("Penduduk");
        mnPenduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPendudukActionPerformed(evt);
            }
        });
        MMaster.add(mnPenduduk);

        MnMahasiswa.setText("Mahasiswa");
        MnMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMahasiswaActionPerformed(evt);
            }
        });
        MMaster.add(MnMahasiswa);

        jMenuBar1.add(MMaster);

        MTransaksi.setText("Transaksi");

        itemBarang.setText("Barang");
        itemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBarangActionPerformed(evt);
            }
        });
        MTransaksi.add(itemBarang);

        jMenuItem2.setText("Pelanggan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MTransaksi.add(jMenuItem2);

        jMenuBar1.add(MTransaksi);

        MLaporan.setText("Laporan");
        jMenuBar1.add(MLaporan);

        MKOnfigurasi.setText("Konfigurasi");
        jMenuBar1.add(MKOnfigurasi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnkeluarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnkeluarActionPerformed

    private void mnPendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPendudukActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnPendudukActionPerformed

    private void MnMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMahasiswaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MnMahasiswaActionPerformed

    private void itemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBarangActionPerformed
        // TODO add your handling code here:
        FrameBarang frameBarang = new FrameBarang();
        frameBarang.setVisible(true);
    }//GEN-LAST:event_itemBarangActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FramePelanggan framePelanggan = new FramePelanggan();
        framePelanggan.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Login;
    private javax.swing.JMenu MKOnfigurasi;
    private javax.swing.JMenu MLaporan;
    private javax.swing.JMenu MMaster;
    private javax.swing.JMenu MTransaksi;
    private javax.swing.JMenu MUtama;
    private javax.swing.JMenuItem MnMahasiswa;
    private javax.swing.JMenuItem itemBarang;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnPenduduk;
    private javax.swing.JMenuItem mnkeluar;
    // End of variables declaration//GEN-END:variables
}
