/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdbaru;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import static pdbaru.koneksi.con;
import static pdbaru.koneksi.stm;

/**
 *
 * @author Nowo
 */
public class frmmhs extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmmhs.class.getName());
    LocalDateTime now = LocalDateTime.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String tgl=now.format(formatter);
    String autonumberparam, autonumbertgl;
    /**
     * Creates new form frmmhs
     */
    public frmmhs() {
        initComponents();
        this.setLocationRelativeTo(null);
        tabelmhs();
        bersih();
        //autonumber();
    }
    private void bersih(){
        txtalamat.setText("");
        txtkota.setText("");
        txtnama.setText("");
        txtnohp.setText("");
        txtnim.setText("");
        autonumber();
       // autonumbertanggal(tgl);
        
    }
    
    private void tabelmhs(){
        ResultSet res;
        DefaultTableModel tb= new DefaultTableModel();
        tb.addColumn("NIM");
        tb.addColumn("Nama Mahasiswa");
        tb.addColumn("Alamat");
        tb.addColumn("No Handphone");
        tb.addColumn("Kota");
        tblmhs.setModel(tb);
        try {
            /*String url ="jdbc:mysql://localhost/dbpw";
            String user="root";
            String pass="";
            con = DriverManager.getConnection(url,user,pass);
            stm = con.createStatement();*/
            koneksi.getKoneksi();
            String query="Select * from tbmahasiswa";
            res=stm.executeQuery(query);
            while (res.next()){
                tb.addRow(new Object[]{
                    res.getString("nim"), 
                    res.getString("nama"),
                    res.getString("alamat"),
                    res.getString("Handphone"),
                    res.getString("kota")
                });
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnohp = new javax.swing.JTextField();
        txtkota = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmhs = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("NIM");

        jLabel2.setText("NAMA");

        jLabel3.setText("ALAMAT");

        jLabel4.setText("NO HANDPHONE");

        jLabel5.setText("KOTA");
        jLabel5.setVerifyInputWhenFocusTarget(false);

        txtnim.setEditable(false);
        txtnim.setText("txtnim");

        txtnama.setText("txtnama");
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamaFocusLost(evt);
            }
        });

        txtalamat.setText("txtalamat");

        txtnohp.setText("txtnohp");

        txtkota.setText("txtkota");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Rubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tblmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmhs.setName("tblmhs"); // NOI18N
        tblmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmhs);

        jButton5.setText("Tutup");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtkota, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtnohp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel6)))))
                                .addGap(0, 42, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtalamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String kode = txtnama.getText();
        autonumberparam(kode);
        /*try {
            koneksi.getKoneksi();
            String query="insert into tbmahasiswa  values ('"+txtnim.getText()+"','"+txtnama.getText()+"','"+txtalamat.getText()+"','"+txtnohp.getText()+"','"+txtkota.getText()+"','"+tgl+"', '"+autonumberparam+"')";
            stm.executeUpdate(query);
            bersih();
            tabelmhs();
        }catch(Exception e) {
            System.err.println("transaksi gagal"+e.getMessage());
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmhsMouseClicked
        // TODO add your handling code here:
        int no=tblmhs.getSelectedRow();
        txtalamat.setText(tblmhs.getValueAt(no, 2).toString());
        txtkota.setText(tblmhs.getValueAt(no, 4).toString());
        txtnama.setText(tblmhs.getValueAt(no, 1).toString());
        txtnohp.setText(tblmhs.getValueAt(no, 3).toString());
        txtnim.setText(tblmhs.getValueAt(no, 0).toString());
    }//GEN-LAST:event_tblmhsMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void autonumber(){
        ResultSet res;
        String strnim;
        Integer intnim;        
        try {
            koneksi.getKoneksi();
            String query="Select nim from tbmahasiswa Order By nim";
            res=stm.executeQuery(query);
            //res.last();
            while (res.next()){
              strnim=res.getString("nim");
              intnim=1000000001+ Integer.parseInt(strnim);
              strnim=String.valueOf(intnim);
              txtnim.setText(strnim.substring(1, 10));
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal"+e.getMessage());
            txtnim.setText("000000001");
        }        
    }
    
    private void autonumberparam(String kode){
        ResultSet res;
        String strnim, strkode;
        Integer intnim;       
        strkode=kode.substring(0,1);
        try {
            koneksi.getKoneksi();
            String query="Select right(Kode,9)as kd from tbmahasiswa where left(nama,1)='"+strkode+"' Order By Kode";
            res=stm.executeQuery(query);
            while (res.next()){
            //res.last();
                strnim=res.getString("kd");
                intnim=1000000001+ Integer.parseInt(strnim);
                strnim=String.valueOf(intnim);
                autonumberparam=strkode+strnim.substring(1, 10);
                jLabel6.setText("Kode : " +autonumberparam);
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal"+e.getMessage());
            autonumberparam=strkode+"000000001";
        }
    }
    
    private void autonumbertanggal(String tgl){
        ResultSet res;
        String strnim, strkode, y, m, d;
        Integer intnim;       
        y=tgl.substring(0,4);
        m=tgl.substring(5,7);
        d=tgl.substring(8,10);
        try {
            koneksi.getKoneksi();
            String query="Select nim from tbmahasiswa where tanggal='"+tgl+"'Order By nim";
            res=stm.executeQuery(query);
            while (res.next()){
              strnim=res.getString("nim");
              intnim=1000000001+ Integer.parseInt(strnim);
              strnim=String.valueOf(intnim);
              txtnim.setText(y+m+d+strnim.substring(5, 10));
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal"+e.getMessage());
            txtnim.setText(y+m+d+"00001");
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Ya ", "Tidak "};
        int choice = JOptionPane.showOptionDialog(
            null,                                
            "Data dengan primary kay " + txtnim.getText() + " Akan dirubah?",   
            "Confirmation Dialog",               
            JOptionPane.YES_NO_OPTION,    
            JOptionPane.QUESTION_MESSAGE,        
            null,                                
            options,                             
            options[0]                           
        );

        if (choice == JOptionPane.YES_OPTION) {
            try {
               koneksi.getKoneksi();
               String query="update tbmahasiswa set  nama = '"+txtnama.getText()+"',alamat = '"+txtalamat.getText()+"',handphone = '"+txtnohp.getText()+"',kota = '"+txtkota.getText()+"' where nim = '"+txtnim.getText()+"'";
               stm.executeUpdate(query);
               bersih();
               tabelmhs();
           }catch(Exception e) {
               System.err.println("transaksi gagal"+e.getMessage());
           }
        } else if (choice == JOptionPane.NO_OPTION) {
            System.out.println("Data tidak jadi dirubah");
            bersih();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Ya ", "Tidak "};
        int choice = JOptionPane.showOptionDialog(
            null,                                
            "Data dengan primary kay " + txtnim.getText() + " Akan dihapus?",   
            "Confirmation Dialog",               
            JOptionPane.YES_NO_OPTION,    
            JOptionPane.QUESTION_MESSAGE,        
            null,                                
            options,                             
            options[0]                           
        );

        if (choice == JOptionPane.YES_OPTION) {
            try {
               koneksi.getKoneksi();
               String query="delete from tbmahasiswa where nim = '"+txtnim.getText()+"'";
               stm.executeUpdate(query);
               bersih();
               tabelmhs();
           }catch(Exception e) {
               System.err.println("transaksi gagal"+e.getMessage());
           }
        } else if (choice == JOptionPane.NO_OPTION) {
            System.out.println("Data tidak jadi dirubah");
            bersih();
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusLost
        // TODO add your handling code here:
        autonumberparam(txtnama.getText());
       // autonumbertanggal(tgl);
    }//GEN-LAST:event_txtnamaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmmhs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmhs;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    private javax.swing.JTextField txtnohp;
    // End of variables declaration//GEN-END:variables
}
