/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhirrentalwarnet;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG G513RM
 */
public class FrameHistoriTransaksi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(
            FrameHistoriTransaksi.class.getName()
        );

    /**
     * Creates new form FrameHistoriTransaksi
     */
    public FrameHistoriTransaksi() {
        initComponents();

        this.setLocationRelativeTo(null);

        loadHistoriTabel();
        hitungDuitHariIni();
        hitungDuitTotal();
    }

    public void loadHistoriTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama PC");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Waktu Mulai");
        model.addColumn("Waktu Selesai");
        model.addColumn("Durasi (Menit)");
        model.addColumn("Total Pendapatan");

        Connection conn = Koneksi.getKoneksi();
        try {
            // Query JOIN Raksasa Laporan Keuangan
            String sql =
                "SELECT r.tran_id, c.pc_name, cust.cust_name, r.start_time, r.end_time, r.duration_minutes, r.total_cost " +
                "FROM rental_tran r " +
                "JOIN computer c ON r.computer_id = c.computer_id " +
                "JOIN customer cust ON r.customer_id = cust.customer_id " +
                "ORDER BY r.start_time DESC";

            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String endTimeStr = rs.getString("r.end_time");
                // Jika waktu selesai masih kosong, tampilkan status sedang bermain
                if (rs.wasNull() || endTimeStr == null) {
                    endTimeStr = "Masih Bermain...";
                }

                model.addRow(new Object[] {
                    rs.getString("r.tran_id"),
                    rs.getString("c.pc_name"),
                    rs.getString("cust.cust_name"),
                    rs.getString("r.start_time"),
                    endTimeStr,
                    rs.getInt("r.duration_minutes"),
                    "Rp " + rs.getLong("r.total_cost"),
                });
            }
            tabelTransaksi.setModel(model);
        } catch (Exception e) {
            System.err.println("Gagal tarik histori: " + e.getMessage());
        }
    }

    public void hitungDuitHariIni() {
        Connection conn = Koneksi.getKoneksi();
        try {
            // Query SUM untuk menghitung semua uang yang masuk di TANGGAL HARI INI
            String sqlSum =
                "SELECT SUM(total_cost) AS total_duit FROM rental_tran WHERE DATE(start_time) = CURDATE()";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sqlSum);

            if (rs.next()) {
                long totalDuit = rs.getLong("total_duit");
                lblPendapatanHariIni.setText(
                    "TOTAL PENDAPATAN HARI INI: Rp " + totalDuit
                );
            }
        } catch (Exception e) {
            System.err.println("Gagal hitung omset harian: " + e.getMessage());
        }
    }

    public void hitungDuitTotal() {
        Connection conn = Koneksi.getKoneksi();
        try {
            // Query SUM untuk menghitung semua uang yang masuk di TOTAL
            String sqlSum =
                "SELECT SUM(total_cost) AS total_duit FROM rental_tran";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sqlSum);

            if (rs.next()) {
                long totalDuit = rs.getLong("total_duit");
                lblPendapatanTotal.setText("TOTAL PENDAPATAN: Rp " + totalDuit);
            }
        } catch (Exception e) {
            System.err.println("Gagal hitung omset harian: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        lblPendapatanHariIni = new javax.swing.JLabel();
        lblPendapatanTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 550));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 550));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("=== HISTORI & LAPORAN KEUANGAN WARNET ===");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(500, 350));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 100));

        tabelTransaksi.setModel(
            new javax.swing.table.DefaultTableModel(
                new Object[][] {
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null },
                },
                new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }
            ) {
                boolean[] canEdit = new boolean[] {
                    false,
                    false,
                    false,
                    false,
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            }
        );
        jScrollPane1.setViewportView(tabelTransaksi);
        if (tabelTransaksi.getColumnModel().getColumnCount() > 0) {
            tabelTransaksi.getColumnModel().getColumn(0).setResizable(false);
            tabelTransaksi.getColumnModel().getColumn(1).setResizable(false);
            tabelTransaksi.getColumnModel().getColumn(2).setResizable(false);
            tabelTransaksi.getColumnModel().getColumn(3).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 395;
        gridBagConstraints.ipady = 97;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 6);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        btnTutup.setBackground(new java.awt.Color(199, 0, 0));
        btnTutup.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnTutup.setForeground(new java.awt.Color(255, 255, 255));
        btnTutup.setText("Tutup");
        btnTutup.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnTutupActionPerformed(evt);
                }
            }
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 483;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(25, 6, 6, 6);
        jPanel1.add(btnTutup, gridBagConstraints);

        lblPendapatanHariIni.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblPendapatanHariIni.setForeground(new java.awt.Color(46, 204, 113));
        lblPendapatanHariIni.setText("Pendapatan hari ini: Rp 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 423;
        gridBagConstraints.insets = new java.awt.Insets(25, 6, 3, 6);
        jPanel1.add(lblPendapatanHariIni, gridBagConstraints);

        lblPendapatanTotal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblPendapatanTotal.setForeground(new java.awt.Color(46, 204, 113));
        lblPendapatanTotal.setText("Total pendapatan: Rp 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 423;
        gridBagConstraints.insets = new java.awt.Insets(25, 6, 3, 6);
        jPanel1.add(lblPendapatanTotal, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane()
        );
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    javax.swing.GroupLayout.Alignment.TRAILING,
                    layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            jPanel1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addContainerGap()
                )
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            jPanel1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addContainerGap(
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE
                        )
                )
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        this.dispose();
    } //GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
            new FrameHistoriTransaksi().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPendapatanHariIni;
    private javax.swing.JLabel lblPendapatanTotal;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
